'use strict';

// Parity + logic tests for the match-rules service. The headline test proves
// `sequenceRatio` matches Python's difflib.SequenceMatcher.ratio() exactly
// across an oracle fixture (fixtures/difflib-ratios.json, generated by Python).

const test = require('node:test');
const assert = require('node:assert');
const fs = require('node:fs');
const path = require('node:path');

const { sequenceRatio, normalise, autoMatchCategory } = require('../services/matchRules');

test('sequenceRatio matches Python difflib across the oracle', () => {
  const oracle = JSON.parse(
    fs.readFileSync(path.join(__dirname, 'fixtures', 'difflib-ratios.json'), 'utf8')
  );
  assert.ok(oracle.length >= 50, 'oracle has enough cases');
  for (const { a, b, ratio } of oracle) {
    const got = sequenceRatio(a, b);
    assert.ok(
      Math.abs(got - ratio) < 1e-9,
      `ratio mismatch for ${JSON.stringify(a)} vs ${JSON.stringify(b)}: js=${got} py=${ratio}`
    );
  }
});

test('normalise lowercases and collapses whitespace', () => {
  assert.equal(normalise('  NETFLIX   #1234 '), 'netflix #1234');
  assert.equal(normalise(''), '');
  assert.equal(normalise(null), '');
  assert.equal(normalise('A\tB\nC'), 'a b c');
});

test('autoMatchCategory: exact wins whether or not fuzzy is enabled', () => {
  const rules = [{ pattern: 'netflix', category_id: 7 }];
  assert.equal(autoMatchCategory('NETFLIX', rules, false), 7);
  assert.equal(autoMatchCategory('netflix', rules, true), 7);
  assert.equal(autoMatchCategory('hulu', rules, false), null);
});

test('autoMatchCategory: fuzzy pass only when enabled, and only when unambiguous', () => {
  const rules = [
    { pattern: 'netflix subscription', category_id: 7 },
    { pattern: 'netflix subscriptionx', category_id: 7 },
  ];
  // close to both rules, both agree -> 7 with fuzzy on, null with fuzzy off
  assert.equal(autoMatchCategory('netflix subscription', rules, false), 7); // exact hit
  assert.equal(autoMatchCategory('netflix subscriptionnn', rules, true), 7);
  assert.equal(autoMatchCategory('netflix subscriptionnn', rules, false), null);

  const conflict = [
    { pattern: 'coffee shop downtown', category_id: 5 },
    { pattern: 'coffee shop downtoxn', category_id: 9 },
  ];
  // both clear the 0.92 bar but disagree -> null
  assert.equal(autoMatchCategory('coffee shop downtown!', conflict, true), null);
});
