'use strict';

// Parity + logic tests for the match-rules service. The headline test proves
// `sequenceRatio` matches Python's difflib.SequenceMatcher.ratio() exactly
// across an oracle fixture (fixtures/difflib-ratios.json, generated by Python).

const test = require('node:test');
const assert = require('node:assert');
const fs = require('node:fs');
const path = require('node:path');

const { sequenceRatio, normalise } = require('../services/matchRules');

test('sequenceRatio matches Python difflib across the oracle', () => {
  const oracle = JSON.parse(
    fs.readFileSync(path.join(__dirname, 'fixtures', 'difflib-ratios.json'), 'utf8')
  );
  assert.ok(oracle.length >= 50, 'oracle has enough cases');
  for (const { a, b, ratio } of oracle) {
    const got = sequenceRatio(a, b);
    assert.ok(
      Math.abs(got - ratio) < 1e-9,
      `ratio mismatch for ${JSON.stringify(a)} vs ${JSON.stringify(b)}: js=${got} py=${ratio}`
    );
  }
});

test('normalise lowercases and collapses whitespace', () => {
  assert.equal(normalise('  NETFLIX   #1234 '), 'netflix #1234');
  assert.equal(normalise(''), '');
  assert.equal(normalise(null), '');
  assert.equal(normalise('A\tB\nC'), 'a b c');
});

// The auto-match RULES (exact wins, the fixed 0.92 fuzzy bar, ambiguity leaves
// the row alone) are asserted against the shipped path — applyAutoMatch, via
// import — in apiTransactions.test.js. They are not re-tested here: this file
// covers the pure pieces those rules are built from.
